stages:
  - sync
  - lint
  - test
  - build
  - deploy

default:
  image: golang:1.16

lint:
  image: golangci/golangci-lint:v1.45
  stage: lint
  script:
    - golangci-lint run --build-tags "$(go env GOOS)" ./...

vet:
  stage: lint
  script:
    - go mod tidy
    - go vet ./...

test:
  stage: test
  script:
    - go mod tidy
    - go test -race ./...

.build-job: &build-job-template
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - when: never
  script:
    - mkdir -p mybinaries
    - go build -o bin/server ./cmd/server
    - go build -o bin/client ./cmd/client
  artifacts:
    name: "${CI_COMMIT_REF_NAME}-${GOOS}-${GOARCH}"
    paths:
      - bin/*

build:linux:amd64:
  <<: *build-job-template
  variables:
    GOOS: linux
    GOARCH: amd64

build:darwin:amd64:
  <<: *build-job-template
  variables:
    GOOS: darwin
    GOARCH: amd64

build:darwin:arm64:
  <<: *build-job-template
  variables:
    GOOS: darwin
    GOARCH: arm64
