stages:
  - sync
  - lint
  - test
  - build
  - deploy

default:
  image: golang:1.16

lint:
  image: golangci/golangci-lint:v1.45
  stage: lint
  script:
    - golangci-lint run ./...

test:
  stage: test
  script:
    - go mod tidy
    - go vet ./...
    - go test -race ./...

build:
  stage: build
  script:
    - mkdir -p mybinaries
    - go build -o bin/server ./cmd/server
    - go build -o bin/client ./cmd/client
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - bin/*
