.build-job: &build-job-template
  script:
    - mkdir -p mybinaries
    - go build -o bin/server ./cmd/server
    - go build -o bin/client ./cmd/client
  artifacts:
    name: "${CI_COMMIT_REF_NAME}-${GOOS}-${GOARCH}"
    paths:
      - bin/*

build:linux:amd64:
  <<: *build-job-template
  variables:
    GOOS: linux
    GOARCH: amd64

build:darwin:amd64:
  <<: *build-job-template
  variables:
    GOOS: darwin
    GOARCH: amd64

build:darwin:arm64:
  <<: *build-job-template
  variables:
    GOOS: darwin
    GOARCH: arm64